#!/bin/bash

#SBATCH --job-name d2q9-bgk
#SBATCH --nodes 2
#SBATCH --ntasks-per-node 2
#SBATCH --time 00:20:00
#SBATCH --partition=teach_cpu
#SBATCH --account=COSC028844
#SBATCH --output d2q9-bgk.out
#SBATCH --exclusive 

module load languages/intel/2018-u3

echo Running on host `hostname`
echo Time is `date`
echo Directory is `pwd`
echo Slurm job ID is $SLURM_JOB_ID
echo This job runs on the following machines:
echo `echo $SLURM_JOB_NODELIST | uniq`

# Enable using `srun` with Intel MPI
export I_MPI_PMI_LIBRARY=/usr/lib64/libpmi.so

#! Run the executable
mpirun ./d2q9-bgk input_128x128.params obstacles_128x128.dat
#./d2q9-bgk input_128x256.params obstacles_128x256.dat
#./d2q9-bgk input_256x256.params obstacles_256x256.dat
#./d2q9-bgk input_1024x1024.params obstacles_1024x1024.dat
